print('what is your name')
name = input()
print('what is your age')
age = int(input())
print('what is your name')
name1 = input()
print('what is your age')
age1 = int(input())
print(age + age1)
print(age == age1)
