student = input("What is your name?")
print(student + 'cant wait to start writing harder programs!')
instructor = input('Who is your favorite instructor?')
print("Your favorite instructor is " + instructor + 'and he is AWESOME.')
team = input("Which team are you on?")
print(team + " team is the best team in all of MEET")
